project:
  type: book

book:
  title: "Beautiful R"
  author: "Caio Lente + Curso-R"
  date: today
  date-format: YYYY-MM-DD
  chapters:
    - index.qmd
    - introduction.qmd

    - part: structure.qmd
      chapters:
        - environment.qmd
        - editors.qmd
        - r-projects.qmd
        - git.qmd

    - part: patterns.qmd
      chapters:
        - packages.qmd
        - dependencies.qmd
        - data.qmd
        - testing.qmd
        - renv.qmd
        - ci-cd.qmd

    - part: style.qmd
      chapters:
        - beauty.qmd
        - pipe.qmd
        - functions.qmd
        - linting.qmd
        - shiny.qmd

    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo

execute:
  freeze: auto
