project:
  type: book

book:
  title: "Beautiful R"
  author: "Caio Lente + Curso-R"
  date: today
  date-format: YYYY-MM-DD
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: flatly
  pdf:
    documentclass: scrreprt



